### ISSUE TITLE
Don't do black magic with /etc/ssowat/conf.json.persistent!

### ISSUE THREAD

**Issue by alexAubin** [YunoHost-Apps/cjdns_ynh#7]
The ADMIN.md doc recommends to: 

>- Copy current sso configuration file to persistent: cp /etc/ssowat/conf.json /etc/ssowat/conf.json.persistent
>- Then edit the persistent file: nano /etc/ssowat/conf.json.persistent
>- Change public to true and add this line under the wordpress.main uris section: "re:^.fc.*". Remember to add a trailing “,” to the above entry.

Sure it works, but this sounds like a UX and security disaster ... This is not practical, and will lead to various issues when the admin uninstall an app, or edit a permission yet nothing happens because the conf.json.persistent will enforce the old values ...

Instead, it should be possible to properly edit the SSO permission/ACL using the `yunohost user permission` CLI ...

**Comment by dkoukoul** [comment]
Hello again @alexAubin. I can not find a way in which my app to be able to edit sso permissions for another app, which makes sense but how could I make it so that it will respond to uris that are cjdns ipv6 addresses? Could there be another way around this?

**Comment by alexAubin** [comment]
Setting an app as public should be as "simple" as `yunohost user permission add wordpress.main visitors`

Adding the additional URI thing is a bit more complex as there's no proper API for this (but i'm wondering about wether or not the underlying technical design of cjdns, or at least the yunohost app, really make sense, but honestly i didnt dig deeper)

Something like:

`yunohost tools shell -c "from yunohost.permission import permission_url; permission_url('wordpress.main', add=["re:^.fc.*"])"`

**Comment by dkoukoul** [comment]
Thanks @alexAubin for all the help!
